version: "3.8"
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: companycheckin
    volumes:
      - vcheckdb:/var/lib/mysql
  api:
    build:
        context: ./api
        dockerfile: ./Dockerfile.dev
    command: npm run start:dev
    ports:
        - 4005:4005
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: admin123
    volumes:
        - ./api:/usr/src/app
        - /usr/src/app/node_modules
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
      # - /usr/src/app/.next
    environment:
      APP_URL: "http://localhost:4005/api/"
    ports:
      - 3005:3005
volumes:
  vcheckdb:
  cache:
    driver: local