export const TICKET_PERMISSION = { READ: "TICKET_READ", WRITE: "TICKET_WRITE" };
export const CHECK_IN_PERMISSION = {
  READ: "CHECK_IN_READ",
  WRITE: "CHECK_IN_WRITE",
};
export const REPORT_PERMISSION = { READ: "REPORT_READ", WRITE: "REPORT_WRITE" };
